/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/CemeteryScene.glb -o src/components/Cementery.jsx -k -K -r public 
*/
import { OverlayItem } from "./OverlayItem";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { degToRad } from "three/src/math/MathUtils";
import { HTML } from "./HTML";

export function Cementery({ html, ...props }) {
  const { nodes, materials } = useGLTF("/models/CemeteryScene.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          name="Cementary_mesh"
          geometry={nodes.Cementary_mesh.geometry}
          material={materials.Cementary_mat1}
        >
          {html && (
            <OverlayItem
              position-x={0.8}
              position-z={-0.8}
              position-y={-0.5}
              rotation-y={degToRad(45)}
              title={"Tent"}
              description={"2 person tent, rest assured you'll be dry."}
              price={"129.99"}
              bgColor={"bg-yellow-500"}
              className={"transition delay-1000"}
            />
            // <HTML>
            //   <h1>Midudev</h1>
            // </HTML>
          )}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/CemeteryScene.glb");
