/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/CemeteryScene.glb -o src/components/Cementery.jsx -k -K -r public 
*/
import { OverlayItem } from "./OverlayItem";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { degToRad } from "three/src/math/MathUtils";
import { HTML } from "./HTML";
import { CharacterProfile } from "./charaters/CharacterProfile";

export function Cementery({ html, ...props }) {
  const { nodes, materials } = useGLTF("/models/CemeteryScene.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          name="Cementary_mesh"
          geometry={nodes.Cementary_mesh.geometry}
          material={materials.Cementary_mat1}
        >
          {html && (
            <OverlayItem
              position-x={-4}
              position-z={-5}
              position-y={8.5}
              rotation-y={degToRad(90)}
              title={"Midudev"}
              description={
                "Detective especialista. Tiene su propia conferencia de programacion. Muy ocupado, no creo que nos pueda ayudar"
              }
              price={"Elegir"}
              bgColor={"bg-yellow-500"}
              className={"transition delay-1000"}
            />
            // <HTML>
            //   <h1>Midudev</h1>
            // </HTML>
          )}
          {html && (
            <CharacterProfile
              title={"Midudev"}
              description={
                "Detective especialista. Tiene su propia conferencia de programacion. Muy ocupado, no creo que nos pueda ayudar"
              }
              onClick={() => console.log("Midudev")}
              imgSrc={
                "https://res.cloudinary.com/lucasangelinodev/image/upload/v1729535268/hackaton/xtjbfhanqsihbg9y4ntx.avif"
              }
            />
          )}

          {html && (
            <OverlayItem
              position-x={-4}
              position-z={4}
              position-y={8.5}
              rotation-y={degToRad(90)}
              title={"Colby"}
              description={
                "Detective especialista. Director en DevX en Cloudinary. Esta muy ocupado trabajando, no creo que nos pueda ayudar"
              }
              price={"Elegir"}
              bgColor={"bg-yellow-500"}
              className={"transition delay-1000"}
            />
            // <HTML>
            //   <h1>Midudev</h1>
            // </HTML>
          )}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/CemeteryScene.glb");
