/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/CemeteryScene.glb -o src/components/Cementery.jsx -k -K -r public 
*/
import { OverlayItem } from "./OverlayItem";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { degToRad } from "three/src/math/MathUtils";
import { HTML } from "./HTML";
import { CharacterProfile } from "./charaters/CharacterProfile";
import { useGameContext } from "../hooks/useContext";
import { LevelOne } from "./levels/LevelOne";
import { LevelTwo } from "./levels/LevelTwo";
import { LevelThree } from "./levels/LevelThree";
import { LevelFour } from "./levels/LevelFour";
import { LevelFive } from "./levels/LevelFive";
import { LevelSix } from "./levels/LevelSix";

export function Cementery({ html, ...props }) {
  const { nodes, materials } = useGLTF("/models/CemeteryScene.glb");
  const { playerName, setOpenChest, setGameLevel, gameLevel, playerPicture } =
    useGameContext();

  const handleClick = () => {
    // setOpenChest(true);
    setGameLevel(1);
  };

  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          name="Cementary_mesh"
          geometry={nodes.Cementary_mesh.geometry}
          material={materials.Cementary_mat1}
        >
          {html && gameLevel === 0 && (
            <CharacterProfile
              position-x={-4}
              position-z={-1}
              position-y={8.5}
              disable={true}
              title={"Midudev"}
              disallow={true}
              description={
                "Detective especialista. Tiene su propia conferencia de programacion llamada MiduConf. Muy ocupado, no creo que nos pueda ayudar"
              }
              onClick={() => console.log("Midudev")}
              imgSrc={
                "https://res.cloudinary.com/lucasangelinodev/image/upload/v1729536847/hackaton/bovozb6b4fetvivs8l9g.avif"
              }
            />
          )}
          {html && gameLevel === 0 && (
            <CharacterProfile
              position-x={-4}
              position-z={-5}
              position-y={8.5}
              title={playerName}
              description={
                "Detective principiante. Sabe algo de programacion. Podria ayudarnos a resolver el caso, pero tendras que ayudarlo con los retos."
              }
              onClick={handleClick}
              imgSrc={playerPicture}
            />
          )}
          {html && gameLevel === 0 && (
            <CharacterProfile
              position-x={-4}
              position-z={3}
              position-y={8.5}
              disable={true}
              title={"Colby"}
              description={
                "Detective especialista. Director en Cloudinary. Experto en analisis de imagenes. Muy ocupado, no creo que nos pueda ayudar"
              }
              onClick={() => console.log("colby")}
              imgSrc={
                "https://res.cloudinary.com/lucasangelinodev/image/upload/v1729535268/hackaton/xtjbfhanqsihbg9y4ntx.avif"
              }
            />
          )}

          {html && gameLevel === 1 && <LevelOne />}
          {html && gameLevel === 2 && <LevelTwo />}
          {html && gameLevel === 3 && <LevelThree />}
          {html && gameLevel === 4 && <LevelFour />}
          {html && gameLevel === 5 && <LevelFive />}
          {html && gameLevel === 6 && <LevelSix />}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/CemeteryScene.glb");
