/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/CemetaryScene2.glb -o src/components/Cementary2.jsx -k -K -r public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CementaryTwo(props) {
  const { nodes, materials } = useGLTF("/models/CemetaryScene2.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          name="cemetery"
          geometry={nodes.cemetery.geometry}
          material={materials.None}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/CemetaryScene2.glb");
